- name: Demo on tags  
  hosts: all 
  tasks:
    - name: Performing WebServer Installation
      debug:
          msg: Web Server Installation . . . 
      tags: WEB

    - name: Performing AppServer Installation
      debug:
          msg: App Server Installation . . . 
      tags: APP   

    - name: App Server tasks done 
      debug:
          msg: App Server Installation Completed 
      tags: APP   
      