# - name: Demo on file Copy 
#   hosts: all 
#   tasks:
#     - name: Copy file with owner and permissions
#       ansible.builtin.copy:
#         src: student.service
#         dest: /home/centos/

- name: Demo on file Copy usong Template 
  hosts: all 
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.template:
        src: student.service
        dest: /home/centos/

  dependencies:
  - role: webserver 
